Update for MediaWiki 1.38
mywikis/MediaWiki-SQLite-to-MySQL pull request #1
Opened 2022-06-15 16:49 UTC by TobiasKaiser

The MySQL post-processing command in csv-to-mysql.php gave me a gew minor errors. Two SQL queries, which I discarded, referenced columns that were dropped from MW's DB schema. I added a query to fix values of the comment_data in the comment table.
I also removed two references to specific outdated MW versions.
In this form, the script worked for me when converting a MW 1.38 SQLite DB with almost no MW plugins installed to MySQL/MariaDB.

2022-06-16 23:08 UTC, jeffw16 requested changes
Thanks for your contribution! I left a few comments

2022-06-16 23:08 UTC, jeffw16 commented on sqlite-to-csv.php
> +$path_to_tables_file = '/path/to/tables-1.xx.txt';
Could we add a distinction that this is for the tables desired in the new version? Otherwise people might think this is the same as the other `xx` which is not true.

2022-06-16 23:08 UTC, jeffw16 commented on csv-to-mysql.php
> +$path_to_schema_file = '/path/to/mediawiki-1.xx-schema-with-confirmacct.sql';
Can we add a distinction here that it's referring to the old schema rather than the new schema?

2022-06-17 09:04 UTC, TobiasKaiser commented on sqlite-to-csv.php
> +$path_to_tables_file = '/path/to/tables-1.xx.txt';
I was under the impression that the purpose of MediaWiki-SQLite-to-MySQL was to transfer data of a MediaWiki installation from SQLite to MySQL. Is it also meant for switching MediaWiki versions in the process? If not, xx should indeed be the same in both files.

2022-06-17 18:05 UTC, jeffw16 commented on sqlite-to-csv.php
> +$path_to_tables_file = '/path/to/tables-1.xx.txt';
@TobiasKaiser it can do both, which is why the distinction should be made.

2022-06-20 21:46 UTC, TobiasKaiser commented
As discussed, the sample filenames now highlight that MediaWiki versions of input and output database can differ.

2022-06-20 22:20 UTC, jeffw16 approved these changes
LGTM

2022-06-20 22:20 UTC, jeffw16 commented
Thanks @TobiasKaiser, merging this PR

2022-06-20 22:20 UTC, merged